version: '3.5'

services:
    tomcatservice:
        container_name: mitomcat 
        image: bitnami/tomcat:latest
        environment:
            TOMCAT_USERNAME: admin
            TOMCAT_PASSWORD: password
            TOMCAT_ALLOW_REMOTE_MANAGEMENT: 1
        ports:
           - 8081:8080
        volumes: # PERSISTENCIA
           - ./tomcat-users.xml:/opt/bitnami/tomcat/conf/tomcat-users.xml


# Mariadb
#   version 4.5
# Trabajo .... Muchos datos -> Volumen (Carpeta con persistencia en el HOST)
#   version 4.6 <- actualizar MariaDB